/**
 * Email Template Builder
 * 
 * Assembles complete email HTML with proper structure for maximum email client compatibility.
 * Handles: content formatting + footer + proper container wrapping.
 */

import { formatForEmail, generateEmailFooter } from './emailFormatting';

/**
 * Processing metrics shown in email footer and saved to messages table
 * All timing values in milliseconds; all values eventually stored in D1
 */
export interface EmailMetrics {
  totalTimeMs: number;         // processing_time_ms: End-to-end time from inbound to reply sent
  ingestTimeMs: number;         // ingest_time_ms: Parsing and coordination overhead
  attachmentTimeMs: number;     // attachment_time_ms: R2 storage time (0 if no attachments)
  openaiUploadTimeMs: number;   // openai_upload_time_ms: File upload to OpenAI (0 if no files)
  aiTimeMs: number;             // ai_response_time_ms: OpenAI generation time
  inputTokens: number;          // tokens_input: Tokens read by AI
  outputTokens: number;         // tokens_output: Tokens generated by AI
  costInDollars: number;        // cost_dollars: Total cost of this message
  reasoningTokens?: number;     // reasoning_tokens: Tokens used for reasoning
  cachedTokens?: number;        // cached_tokens: Input tokens served from cache
  model?: string;               // model: AI model used
  serviceTier?: string;         // service_tier: OpenAI service tier
  reasoningEffort?: string;     // reasoning_effort: Reasoning effort level
}

/**
 * Build complete email HTML with content + footer
 * 
 * Returns both text and HTML versions properly structured.
 * This is the single source of truth for email assembly.
 */
export function buildEmailWithFooter(
  aiResponseContent: string,
  metrics: EmailMetrics
): { textBody: string; htmlBody: string } {
  
  // 1. Generate footer
  const footer = generateEmailFooter(
    metrics.totalTimeMs,
    metrics.ingestTimeMs,
    metrics.attachmentTimeMs,
    metrics.openaiUploadTimeMs,
    metrics.aiTimeMs,
    metrics.inputTokens,
    metrics.outputTokens,
    metrics.costInDollars,
    metrics.reasoningTokens,
    metrics.cachedTokens,
    metrics.model,
    metrics.serviceTier,
    metrics.reasoningEffort
  );

  // 2. Text version: simple concatenation
  const textBody = aiResponseContent + footer.text;

  // 3. HTML version: bare semantic content + footer, no styling wrapper.
  //    We rely on the recipient's mail client for default rendering.
  const formattedContent = formatForEmail(aiResponseContent);
  const htmlBody = `${formattedContent}${footer.html}`.trim();

  return { textBody, htmlBody };
}

/**
 * Build simple error email (no footer)
 */
export function buildErrorEmail(
  errorMessage: string,
  technicalDetails?: string
): { textBody: string; htmlBody: string } {
  
  const textBody = `Hi there,

We ran into a problem processing your email.

${technicalDetails ? `Error details: ${technicalDetails}\n\n` : ''}Please try again later.`;

  const htmlBody = `<p>Hi there,</p>
<p>We ran into a problem processing your email.</p>
${technicalDetails ? `<p>Error details:</p>\n<pre>${technicalDetails.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>\n` : ''}<p>Please try again later.</p>`;

  return { textBody, htmlBody };
}

/**
 * Build simple text email (like "missing system prompt" error)
 */
export function buildSimpleEmail(message: string): { textBody: string; htmlBody: string } {
  // Escape so a stray '<' in the message doesn't get parsed as markup.
  const escaped = message
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
  return {
    textBody: message,
    htmlBody: `<p>${escaped}</p>`,
  };
}

