/**
 * Generate email footer with processing metrics
 * 
 * All metrics shown here are also saved to the messages table for tracking:
 * - totalTimeMs → processing_time_ms (end-to-end processing)
 * - ingestTimeMs → ingest_time_ms (parsing, coordination overhead)
 * - attachmentTimeMs → attachment_time_ms (R2 storage time)
 * - openaiUploadTimeMs → openai_upload_time_ms (file upload to OpenAI)
 * - aiTimeMs → ai_response_time_ms (OpenAI generation time)
 * - inputTokens → tokens_input (tokens read by AI)
 * - outputTokens → tokens_output (tokens generated by AI)
 * - reasoningTokens → reasoning_tokens (tokens used for reasoning)
 * - cachedTokens → cached_tokens (input tokens from cache)
 * - costInDollars → cost_dollars (total cost of this message)
 * - model → model (AI model used, e.g., "gpt-5.1")
 * - serviceTier → service_tier (OpenAI tier used)
 * - reasoningEffort → reasoning_effort (reasoning level)
 * 
 * Returns both text and HTML versions for email client compatibility
 */
export function generateEmailFooter(
  totalTimeMs: number,
  ingestTimeMs: number,
  attachmentTimeMs: number,
  openaiUploadTimeMs: number,
  aiTimeMs: number,
  inputTokens: number,
  outputTokens: number,
  costInDollars: number,
  reasoningTokens?: number,
  cachedTokens?: number,
  model?: string,
  serviceTier?: string,
  reasoningEffort?: string
): { text: string; html: string } {
  
  // Format total time for readability (switch to seconds if over 1 second)
  const totalTimeDisplay = totalTimeMs >= 1000 
    ? `${(totalTimeMs / 1000).toFixed(2)} seconds`
    : `${totalTimeMs}ms`;

  // Build bullet list conditionally (only show steps that actually occurred)
  const bullets: string[] = [
    `Received and parsed your email: ${ingestTimeMs}ms`
  ];
  
  if (attachmentTimeMs > 0) {
    bullets.push(`Saved attachments to storage: ${attachmentTimeMs}ms`);
  }
  
  if (openaiUploadTimeMs > 0) {
    bullets.push(`Uploaded files for AI analysis: ${openaiUploadTimeMs}ms`);
  }
  
  bullets.push(`AI generated response: ${aiTimeMs}ms`);

  // Build token usage string with detailed breakdown
  let tokenUsage = `read ${inputTokens.toLocaleString()} tokens`;
  if (cachedTokens && cachedTokens > 0) {
    tokenUsage += ` (${cachedTokens.toLocaleString()} cached)`;
  }
  tokenUsage += `, generated ${outputTokens.toLocaleString()} tokens`;
  if (reasoningTokens && reasoningTokens > 0) {
    tokenUsage += ` (${reasoningTokens.toLocaleString()} reasoning)`;
  }

  // Add AI configuration details if available
  const aiConfig: string[] = [];
  if (model) aiConfig.push(model);
  if (reasoningEffort) aiConfig.push(`${reasoningEffort} effort`);
  if (serviceTier) aiConfig.push(serviceTier);
  const aiConfigStr = aiConfig.length > 0 ? ` • ${aiConfig.join(', ')}` : '';

  // Plain text version
  const text = `\n\n---\nRally processed this email in ${totalTimeDisplay}:\n` +
    bullets.map(b => `• ${b}`).join('\n') +
    `\n\nAI Usage: $${costInDollars.toFixed(4)} (${tokenUsage})${aiConfigStr}`;

  // HTML version - simple table for maximum email client compatibility
  // Wrapped in div to avoid loose br tags that Postmark might strip
  const html = `
<div style="margin-top: 24px;">
<table style="padding-top: 12px; border-top: 1px solid #e0e0e0; font-family: Arial, sans-serif; font-size: 11px; color: #888888; width: 100%;">
  <tr>
    <td colspan="2" style="padding-bottom: 8px; font-weight: 600; color: #666666;">Rally processed this email in ${totalTimeDisplay}:</td>
  </tr>
  ${bullets.map(b => `<tr><td style="padding: 2px 0; padding-left: 8px; vertical-align: top;">&bull;</td><td style="padding: 2px 0;">${b}</td></tr>`).join('')}
  <tr>
    <td colspan="2" style="padding-top: 8px; font-weight: 600; color: #666666;">AI Usage: <span style="font-weight: 400; color: #888888;">$${costInDollars.toFixed(4)} (${tokenUsage})${aiConfigStr}</span></td>
  </tr>
</table>
</div>
`;

  return { text, html };
}

